In [36]:
import torch
import numpy as np

# Check status
torch.cuda.is_available()

True

In [37]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [38]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

In [39]:
x_ones = torch.ones_like(x_data)
x_ones

tensor([[1, 1],
        [1, 1]])

In [40]:
x_rand = torch.rand_like(x_data, dtype=torch.float)
x_rand

tensor([[0.1786, 0.0200],
        [0.7260, 0.3018]])

In [41]:
tensor = torch.rand(size=(7, 2), dtype=torch.float64)

print(f"Tensor: {tensor}")
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

if torch.cuda.is_available():
    tensor = tensor.to('cuda')
    
print(f"Device tensor is stored on: {tensor.device}")
    

Tensor: tensor([[0.3809, 0.9180],
        [0.8659, 0.6703],
        [0.5034, 0.3071],
        [0.0956, 0.5843],
        [0.9242, 0.9661],
        [0.4905, 0.6372],
        [0.6407, 0.7861]], dtype=torch.float64)
Shape of tensor: torch.Size([7, 2])
Datatype of tensor: torch.float64
Device tensor is stored on: cpu
Device tensor is stored on: cuda:0


In [53]:
tensor = torch.ones(4, 4)
tensor[:,1] = 0
print('First row: ',tensor[0])
print('First column: ', tensor[:, 0])
print('Last column:', tensor[..., -1])
print(tensor)

tensor1 = torch.ones(4, 4)
tensor1[:,1] = 3

t1 = torch.cat([tensor, tensor1, tensor], dim=0)
print(t1.shape)
t1

First row:  tensor([1., 0., 1., 1.])
First column:  tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
torch.Size([12, 4])


tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 3., 1., 1.],
        [1., 3., 1., 1.],
        [1., 3., 1., 1.],
        [1., 3., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [43]:
tensor1 = torch.rand((3, 4))
tensor2 = torch.rand((4, 5))
print(tensor1)
print(tensor2)
print(tensor1 @ tensor2)

tensor([[0.3740, 0.1739, 0.3645, 0.3066],
        [0.4453, 0.7838, 0.9136, 0.6959],
        [0.5832, 0.3708, 0.6304, 0.7701]])
tensor([[0.1926, 0.0270, 0.3762, 0.0288, 0.3674],
        [0.0997, 0.5090, 0.3818, 0.8869, 0.0631],
        [0.1345, 0.4386, 0.0651, 0.4619, 0.6626],
        [0.3323, 0.3850, 0.8120, 0.0930, 0.5854]])
tensor([[0.2402, 0.3765, 0.4797, 0.3619, 0.5693],
        [0.5180, 1.0796, 1.0914, 1.1947, 1.2259],
        [0.4899, 0.7775, 1.0273, 0.7085, 1.1062]])
