# Prototype: Data Visualization

In [1]:
import open3d as o3d
import numpy as np

import torch
import torch.nn as nn
from torch.autograd import Variable

import sys
sys.path.insert(0, '../impl/utils/')
import voxel_processing as vp

# device will determine whether to run the training on GPU or CPU
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
device

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


device(type='cuda')

In [2]:
# Load datasets
data = vp.read_dataset_from_path('../data/voxel_data/')
data = vp.prepare_dataset(data)

Reading: ../data/voxel_data/voxel_grid_1.obj
Reading: ../data/voxel_data/voxel_grid_0.omap
Reading: ../data/voxel_data/voxel_grid_1.offsetvec
Reading: ../data/voxel_data/voxel_grid_0.gridpoints
Reading: ../data/voxel_data/voxel_grid_0.obj
Reading: ../data/voxel_data/voxel_grid_1.omap
Reading: ../data/voxel_data/voxel_grid_0.offsetvec
Reading: ../data/voxel_data/voxel_grid_1.gridpoints
2 dataset(s) have been processed. 
2 dataset(s) have been prepared. 


In [3]:
mesh = data[0][0]
plane = np.array([1, 1, 1, 0])
mesh

TriangleMesh with 6130 points and 8448 triangles.

In [4]:
A = plane[0]
B = plane[1]
C = plane[2]
D = plane[3]

coords_mat = np.array([[-1., -1.], [-1., 1.], [1., -1.], [1., 1.]])
coords_mat

array([[-1., -1.],
       [-1.,  1.],
       [ 1., -1.],
       [ 1.,  1.]])

In [5]:
zs = (-coords_mat @ plane[0:2] - plane[3]) / plane[2]
zs = zs.reshape(-1, 1)
zs

array([[ 2.],
       [ 0.],
       [ 0.],
       [-2.]])

In [6]:
plane_vertices = np.concatenate([coords_mat, zs], axis=1)
plane_vertices

array([[-1., -1.,  2.],
       [-1.,  1.,  0.],
       [ 1., -1.,  0.],
       [ 1.,  1., -2.]])

In [7]:
plane_triangles = np.array([[0, 1, 2], [2, 1, 3], [0, 2, 1], [1, 2, 3]])
plane_triangles

array([[0, 1, 2],
       [2, 1, 3],
       [0, 2, 1],
       [1, 2, 3]])

In [8]:
# Create a mesh for the plane
normal = plane[0:3] / np.linalg.norm(plane[0:3])
plane_mesh = o3d.geometry.TriangleMesh()
plane_mesh.vertices = o3d.utility.Vector3dVector(plane_vertices)
plane_mesh.triangles = o3d.utility.Vector3iVector(plane_triangles)
plane_mesh.compute_triangle_normals()

mesh.compute_vertex_normals()
plane_mesh.paint_uniform_color([0.3, 0.3, 0.6])

import open3d.visualization as vis
# vis.draw_geometries([plane_mesh, mesh])

In [9]:
# import open3d.visualization as vis

# # Visualize the plane
# mat_plane = vis.rendering.MaterialRecord()
# mat_plane.shader = 'defaultLitSSR'
# mat_plane.base_color = [0., 0.467, 0., 0.2]
# mat_plane.base_roughness = 0.
# mat_plane.base_reflectance = 0.
# mat_plane.base_clearcoat = 1.
# mat_plane.thickness = 1.
# mat_plane.transmission = 1.
# mat_plane.absorption_distance = 10
# mat_plane.absorption_color = [0.5, 0, 0.5]

# geoms = [{'name': 'plane', 'geometry': plane_mesh, 'material': mat_plane}, {'name': 'object', 'geometry': mesh}]

# vis.draw(geoms, title='Hi')

In [10]:
import visualization as prsvis
prsvis.visualize_planar_symmetry(mesh, np.array([1, 0, 0, 0]))

standard_AABB=AxisAlignedBoundingBox: min: (-1, -1, -1), max: (1, 1, 1)
[visualization.py] Drawing symmetry plane [1 0 0 0]
